apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todos-app
  namespace: argocd
spec:
  project: default
  source:
    # GitLab Container Registry 地址
    repoURL: oci://registry.gitlab.com/jerrybai/todos-helm
    # Chart 版本号，可以使用具体版本或标签
    # 使用语义化版本范围，自动选择最新的0.1.x版本
    targetRevision: ">=0.1.0 <0.2.0"
    # Chart 名称
    chart: todo-chart

  destination:
    server: https://kubernetes.default.svc
    namespace: todos-helm
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
